version: "3.8"

networks:
  os-net:
    driver: bridge

services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
    networks:
      - os-net
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.12.0
    container_name: opensearch-dashboards
    depends_on:
      opensearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    volumes:
      - ./dashboards:/usr/share/opensearch-dashboards/config
    environment:
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    networks:
      - os-net

  # Auto-creates index template + index pattern in Dashboards
  setup:
    image: curlimages/curl:8.5.0
    container_name: setup
    depends_on:
      opensearch:
        condition: service_healthy
    volumes:
      - ./setup/setup-index-pattern.sh:/setup.sh:ro
    entrypoint: ["sh", "/setup.sh"]
    networks:
      - os-net
    restart: "no"

  fluent-bit:
    image: fluent/fluent-bit:2.2
    container_name: fluent-bit
    depends_on:
      opensearch:
        condition: service_healthy
    volumes:
      - /tmp:/logs:ro
      - /Users/akshay.chauhan/Desktop/freecharge/axis-los-qe/test-output:/test-logs:ro
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
    networks:
      - os-net
